### ISSUE TITLE
Issue in loading the Language Vote App v3 - final step

### ISSUE THREAD

**Issue by kavithanagaraj3** [N4si/K8s-voting-app#7]
Hi,
I had deployed backend service as a ClusterIP. And configured same clusterIp in frontend deployement as env variable.
I am able to resolve service from front end pod as well as i am able to curl the apis from front end pod.

Still web page is not loading properly it shows

please check and let us know how can we access the Vote App v3 properly and we can vote for the language.

Please find the screenshot below.
![voting-app](https://github.com/N4si/K8s-voting-app/assets/141347848/e8838fff-ec3c-42d0-9d24-faa9ff025dde)

**Comment by N4si** [comment]
Solution: https://github.com/N4si/K8s-voting-app/issues/1

**Comment by kavithanagaraj3** [comment]
Issue is fixed thank you!!!!
